尽管 Promise.all([ .. ]) 协调多个并发 Promise 的运行，并假定所有 Promise 都需要完成，但有时候你会想只响应“第一个跨过终点线的 Promise”，而抛弃其他 Promise。

这种模式传统上称为门闩，但在 Promise 中称为竞态。

>虽然“只有第一个到达终点的才算胜利”这个比喻很好地描述了其行为特性，但遗憾的是，由于竞态条件通常被认为是程序中的 bug（参见第 1 章），所以从某种程度上说，
“竞争”这个词已经是一个具有固定意义的术语了。不要混淆了 Promise.race([..])和竞态条件。

Promise.race([ .. ]) 也接受单个数组参数。这个数组由一个或多个 Promise、thenable 或立即值组成。立即值之间的竞争在实践中没有太大意义，
因为显然列表中的第一个会获胜，就像赛跑中有一个选手是从终点开始比赛一样！

与 Promise.all([ .. ]) 类似，一旦有任何一个 Promise 决议为完成，Promise.race([ .. ]) 就会完成；一旦有任何一个 Promise 决议为拒绝，它就会拒绝。

>一项竞赛需要至少一个“参赛者”。所以，如果你传入了一个空数组，主race([..]) Promise 永远不会决议，而不是立即决议。这很容易搬起石头砸自己的脚！
ES6 应该指定它完成或拒绝，抑或只是抛出某种同步错误。遗憾的是，因为 Promise 库在时间上早于 ES6 Promise ，它们不得已遗留了这个问题，所以，要注意，永远不要递送空数组。

再回顾一下前面的并发 Ajax 例子，不过这次的 p1 和 p2 是竞争关系：
```
// request(..)是一个Promise-aware Ajax 工具
// 就像我们再本章前面定义的一样

var p1 = request("http://some.url.1")
var p1 = request("http://some.url.2")

Promise.race([p1, p2])
.then(function(msgs){
  // 这里， p1 和 p2 完成并把它们的消息传入
  return request(
    "http://some.url.3/?v=" + msgs.join(',')
  )
})
.then(function(msg){
  console.log(msg)
})
```
因为只有一个 promise 能够取胜，所以完成值是单个消息，而不是像对 Promise.all([..]) 那样的是一个数组。

## 1.超时竞赛

我们之前看到过这个例子，其展示了如何使用 Promise.race([ .. ]) 表达 Promise 超市模式：
```
// foo()是一个支持 Promise 的函数
// 前面定义的 timeoutPromise(..) 返回一个 promise,
// 这个 promise 会在指定延时之后拒绝

// 为 foo() 设定超时
Promise.race([
  foo(), // 启动 foo()
  timeoutPromise(3000) // 给它3秒钟
])
.then(
  function(){
    // foo(..)按时完成！
  },
  function(err){
    // 要么foo()被拒绝，要么只是没能按时完成，
    // 因此要查看 err 了解具体原因
  }
)
```
在多数情况下，这个超时模式能够很好地工作。但是，还有一些微妙的情况需要考虑，并且坦白地说，对于 Promise.race([ .. ]) 和 Promise.all([ .. ]) 也都是如此。

## 2. finally

一个关键问题是：“那些被丢弃或忽略的 promise 会发生什么呢？” 我们并不是从性能的角度提出这个问题的——通常最终它们会被垃圾回收——而是从行为的角度（副作用等）。
Promise 不能被取消，也不应该被取消，因为那会摧毁 3.8.5 节讨论的外部不变性原则，所以它们只能被默默忽略。

那么如果前面例子中的 foo() 保留了一些要用的资源，但是出现了超时，导致这个 promise 被忽略，这又会怎样呢？在这种模式中，会有什么为超时后主动释放这些保留资源提供任何支持，
或者取消任何可能产生的副作用吗？如果你想要的只是记录下 foo() 超时这个事实，又会如何呢？

有些开发者提出，Promise 需要一个 finally(..) 回调注册，这个回调在 Promise 决议后总是会被调用，并且允许你执行任何必要的清理工作。目前，规范还没有支持这一点，
不过在 ES7+ 中也许可以。只好等等看了。

它看起来可能类似于：
```
var p = Promise.resolve(42)

p.then(something)
.finally(cleanup)
.then(another)
.finally(cleanup)
```

>在各种各样的 Promise 库 中，finally(..) 还是会创建并返回一个新的 Promise（以支持链接继续）。如果 cleanup(..) 函数要返回一个 Promise 的话，这个 promise就会被连接到链中，
这意味着这里还是会有前面讨论过的未处理拒绝问题。

同时，我们可以构建一个静态辅助工具来支持查看（而不影响）Promise 的决议：
```
// polyfill 安全的 guard 检查
if(!Promise.observe){
  Promise.observe = function(pr, cb){
    // 观察pr的决议
    pr.then(
      function.fulfilled(msg){
        // 安排异步回调（作为Job）
        Promise.resolve(msg).then(cb)
      },
      function rejected(err){
        // 安排异步回调（作为Job）
        Promise.resolve(err).then(cb)
      }
    );

    // 返回最初的 promise
    return pr;
  }
}
```
下面是如何在前面的超时例子中使用这个工具：
```
Promise.race([
  Promise.observe(
    foo(),  // 试着运行 foo()
    function cleanup(msg) {
      // 在 foo() 之后清理，即使它没有在超时之前完成
    }
  ),
  timeoutPromise(3000) // 给它3秒钟
])
```
这个辅助工具 Promise.observe(..) 只是用来展示可以如何查看 Promise 的完成而不对其产生影响。其他的 Promise 库有自己的解决方案。
不管如何实现，你都很可能遇到需要确保 Promise 不会被意外默默忽略的情况。